/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package customcompiler;

import javax.swing.JTextArea;



/**
 *
 * @author reynaldoalvarez
 */
public class LexerTestCasesFrame extends javax.swing.JFrame {

    /**
     * Creates new form LexerTestCasesFrame
     */
    public LexerTestCasesFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitle1 = new javax.swing.JLabel();
        checkBox2 = new javax.swing.JCheckBox();
        labelInput = new javax.swing.JLabel();
        labelInput1 = new javax.swing.JLabel();
        checkBox4 = new javax.swing.JCheckBox();
        checkBox3 = new javax.swing.JCheckBox();
        checkBox1 = new javax.swing.JCheckBox();
        buttonConfirm = new javax.swing.JButton();
        checkBox5 = new javax.swing.JCheckBox();
        checkBox6 = new javax.swing.JCheckBox();
        checkBox7 = new javax.swing.JCheckBox();
        checkBox8 = new javax.swing.JCheckBox();
        checkBox9 = new javax.swing.JCheckBox();
        checkBox10 = new javax.swing.JCheckBox();
        checkBox11 = new javax.swing.JCheckBox();
        checkBox12 = new javax.swing.JCheckBox();
        checkBox13 = new javax.swing.JCheckBox();
        menuLexer = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        menuItemExit = new javax.swing.JMenuItem();
        menuHelp = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Custom Compiler: Lexer");
        setLocation(new java.awt.Point(20, 20));
        setName("LexerTestCasesFrame"); // NOI18N
        setPreferredSize(new java.awt.Dimension(730, 550));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelTitle1.setFont(new java.awt.Font("Helvetica Neue", 3, 36)); // NOI18N
        labelTitle1.setText("Test Cases");
        labelTitle1.setAlignmentX(45.0F);
        labelTitle1.setAlignmentY(15.0F);
        getContentPane().add(labelTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 200, -1));

        checkBox2.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        checkBox2.setText("Chars and Quotes");
        checkBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(checkBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, -1, -1));

        labelInput.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        labelInput.setText("Error Cases");
        getContentPane().add(labelInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, -1, -1));

        labelInput1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        labelInput1.setText("Working Cases");
        getContentPane().add(labelInput1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));

        checkBox4.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        checkBox4.setText("Illegal Input");
        checkBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBox4ActionPerformed(evt);
            }
        });
        getContentPane().add(checkBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 230, -1, -1));

        checkBox3.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        checkBox3.setText("Alan's Case");
        checkBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBox3ActionPerformed(evt);
            }
        });
        getContentPane().add(checkBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, -1, -1));

        checkBox1.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        checkBox1.setText("Empty Brackets");
        checkBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(checkBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, -1));

        buttonConfirm.setFont(new java.awt.Font("Helvetica", 0, 16)); // NOI18N
        buttonConfirm.setText("Confirm");
        buttonConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonConfirmActionPerformed(evt);
            }
        });
        getContentPane().add(buttonConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 460, 100, 30));

        checkBox5.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        checkBox5.setText("Random");
        checkBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBox5ActionPerformed(evt);
            }
        });
        getContentPane().add(checkBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 260, -1, -1));

        checkBox6.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        checkBox6.setText("Print Statement (StringExpr)");
        checkBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBox6ActionPerformed(evt);
            }
        });
        getContentPane().add(checkBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, -1, -1));

        checkBox7.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        checkBox7.setText("Print Statement (IntExpr)");
        checkBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBox7ActionPerformed(evt);
            }
        });
        getContentPane().add(checkBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, -1));

        checkBox8.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        checkBox8.setText("Print Statement (ID)");
        checkBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBox8ActionPerformed(evt);
            }
        });
        getContentPane().add(checkBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, -1, -1));

        checkBox9.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        checkBox9.setText("Print Statement (BooleanExpr)");
        checkBox9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBox9ActionPerformed(evt);
            }
        });
        getContentPane().add(checkBox9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, -1, -1));

        checkBox10.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        checkBox10.setText("Variable Declaration");
        checkBox10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBox10ActionPerformed(evt);
            }
        });
        getContentPane().add(checkBox10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, -1, -1));

        checkBox11.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        checkBox11.setText("Assignment Statement");
        checkBox11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBox11ActionPerformed(evt);
            }
        });
        getContentPane().add(checkBox11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, -1, -1));

        checkBox12.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        checkBox12.setText("If Statement");
        checkBox12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBox12ActionPerformed(evt);
            }
        });
        getContentPane().add(checkBox12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, -1, -1));

        checkBox13.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        checkBox13.setText("While Statement");
        checkBox13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBox13ActionPerformed(evt);
            }
        });
        getContentPane().add(checkBox13, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, -1, -1));

        menuLexer.setToolTipText("");

        menuFile.setText("File");

        menuItemExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        menuItemExit.setText("Exit");
        menuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemExitActionPerformed(evt);
            }
        });
        menuFile.add(menuItemExit);

        menuLexer.add(menuFile);

        menuHelp.setText("Help");
        menuLexer.add(menuHelp);

        setJMenuBar(menuLexer);

        getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemExitActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lexer().setVisible(true);
            }
        });
        this.dispose();
    }//GEN-LAST:event_menuItemExitActionPerformed

    private void checkBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBox2ActionPerformed

    private void checkBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBox4ActionPerformed

    private void checkBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBox3ActionPerformed

    private void checkBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBox1ActionPerformed

    private void buttonConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonConfirmActionPerformed
        
        Lexer lex = new Lexer();
        JTextArea inputArea = lex.getInputArea();
        
        
        if(checkBox1.isSelected()) {
            inputArea.append("{}$");
        }
        
        if(checkBox2.isSelected()) {
            inputArea.append("print()&"
               + "if(a)$"
               + "while(true)$\n"
               + "{print(\"b\")}$");
        }
        
        if(checkBox3.isSelected()) {
            inputArea.append("{}$\n" +
            "{{{{{{}}}}}}$\n" +
            "{{{{{{}}} /* comments are ignored */ }}}}$\n" +
            "{ /* comments are still ignored */ int @}$");
        }
        
        if(checkBox4.isSelected()) {
            inputArea.append("{int @}$"
                + "{\"$\"}$");
        }
        
        if(checkBox5.isSelected()) {
            inputArea.append("{\n"
                    + "\t int a = 4"
                    + "\n"
                    + "\n"
                    + "\t int b \n\n"
                    + "\t b = a + a"
                    + "\n"
                    + "}$");
        }
        
        if(checkBox6.isSelected()) {
            inputArea.append("{ /* PrintStatement(StringExpr) */\n"
                + "\t print( \" asdasdas \" )"
                + "\n"
                + "}$");
        }
        
        if(checkBox7.isSelected()) {
            inputArea.append("{ /* PrintStatement(IntExpr) */\n"
                + "\t print( 2 + 2 )"
                + "\n"
                + "}$");
        }
    
        if(checkBox8.isSelected()) {
            inputArea.append("{ /* PrintStatement(ID) */\n"
                + "\t print(z)"
                + "\n"
                + "}$");
        }
        
        if(checkBox9.isSelected()) {
            inputArea.append("{ /* PrintStatement(BooleanExpr) */\n"
                + "\t print( ( w == w ) )"
                + "\n"
                + "\t print( (5 + 2 != 6 + 4) )"
                + "\n"
                + "\t print( (\"dlaslkdmasd\" != \" dasdasd \") )"
                + "\n"
                + "\t print( (a == 3) )"
                + "\n"
                + "\t print( (\"sadklmasd\" == a) )"
                + "\n"
                + "\t print( (\"sd\" != 2) )"
                + "\n"
                + "}$"); 
        }
        
        if(checkBox10.isSelected()) {
            inputArea.append("{ /* Variable Declaration */\n"
                    + "\t int a"
                    + "\n"
                    + "\t string b"
                    + "\n"
                    + "\t boolean c"
                    + "\n"
                    + "}$");
        }
        
        if(checkBox11.isSelected()) {
            inputArea.append("{ /* Assignment Statement */\n"
                    + "\t a = b"
                    + "\n"
                    + "\t b = 2"
                    + "\n"
                    + "\t c = 5 + 2"
                    + "\n"
                    + "\t d = \"burger\""
                    + "\n"
                    + "\t a = true"
                    + "\n"
                    + "\t c = false"
                    + "\n"
                    + "}$");
        }
        
        if(checkBox12.isSelected()) {
            inputArea.append("{ /* if Statement */\n"
                    + "\t if(5 + 2 != 6 + 4) {  }"
                    + "\n"
                    + "}$");
        }
        
        if(checkBox13.isSelected()) {
            inputArea.append("{ /* while Statement */\n"
                    + "\t while(true) { /* What now */ }"
                    + "\n"
                    + "}$");
        }        
        
        lex.setVisible(true);
        lex.setEnabled(true);
        this.dispose();
    }//GEN-LAST:event_buttonConfirmActionPerformed

    private void checkBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBox5ActionPerformed

    private void checkBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBox6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBox6ActionPerformed

    private void checkBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBox7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBox7ActionPerformed

    private void checkBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBox8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBox8ActionPerformed

    private void checkBox9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBox9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBox9ActionPerformed

    private void checkBox10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBox10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBox10ActionPerformed

    private void checkBox11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBox11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBox11ActionPerformed

    private void checkBox12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBox12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBox12ActionPerformed

    private void checkBox13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBox13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBox13ActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(LexerTestCasesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(LexerTestCasesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(LexerTestCasesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(LexerTestCasesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new LexerTestCasesFrame().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonConfirm;
    private javax.swing.JCheckBox checkBox1;
    private javax.swing.JCheckBox checkBox10;
    private javax.swing.JCheckBox checkBox11;
    private javax.swing.JCheckBox checkBox12;
    private javax.swing.JCheckBox checkBox13;
    private javax.swing.JCheckBox checkBox2;
    private javax.swing.JCheckBox checkBox3;
    private javax.swing.JCheckBox checkBox4;
    private javax.swing.JCheckBox checkBox5;
    private javax.swing.JCheckBox checkBox6;
    private javax.swing.JCheckBox checkBox7;
    private javax.swing.JCheckBox checkBox8;
    private javax.swing.JCheckBox checkBox9;
    private javax.swing.JLabel labelInput;
    private javax.swing.JLabel labelInput1;
    private javax.swing.JLabel labelTitle1;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenu menuHelp;
    private javax.swing.JMenuItem menuItemExit;
    private javax.swing.JMenuBar menuLexer;
    // End of variables declaration//GEN-END:variables
}
